# 接口配置
bigfun:
  # bigfun 的 cookies 值 可以通过浏览器 F12 获得
  cookies:  sid=xxx; DedeUserID=xxx; DedeUserID__ckMd5=xxxx; SESSDATA=xxxx; bili_jct=xxx; _csrf=xxxxx; ...
  # bigfun 请求中 header 中的 x-csrf-token 值 可以通过浏览器 F12 获得
  csrfToken: xxxxxxxxxxxxxxxxxxxxxxxxx

# QQ 机器人配置
bot:
  qq: 222222222222 # QQ 号
  password: 123456 # QQ 密码
  group: 2222222222 # 群号